[package]
name = "multisig-enhanced-meta"
version = "0.1.0"
authors = [ "Gaupa Labs",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.multisig-enhanced]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.2"

[dependencies.elrond-wasm-debug]
version = "0.27.2"
